// printfn $"Solution for Day 1 (Part 1): %A{Day01.Part01.solution}"
// printfn $"Solution for Day 1 (Part 2): %A{Day01.Part02.solution}"
// printfn $"Solution for Day 2 (Part 1): %A{Day02.Part01.solution}"
// printfn $"Solution for Day 2 (Part 2): %A{Day02.Part02.solution}"
// printfn $"Solution for Day 3 (Part 1): %A{Day03.Part01.solution}"
// printfn $"Solution for Day 3 (Part 2): %A{Day03.Part01.solution}"
// printfn $"Solution for Day 4 (Part 1): %A{Day04.Part01.solution}"
// printfn $"Solution for Day 4 (Part 2): %A{Day04.Part02.solution}"
// printfn $"Solution for Day 5 (Part 1): %A{Day05.Part01.solution}"
// printfn $"Solution for Day 5 (Part 2): %A{Day05.Part02.solution}"
printfn $"Solution for Day 6 (Part 1): %A{Day06.Part01.solution}"
printfn $"Solution for Day 6 (Part 2): %A{Day06.Part02.solution}"